# Number of days of inactivity before an issue becomes stale
daysUntilStale: 90
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 14
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked stale because of inactivity.

  It will be closed if no further activity occurs.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false

issues:
  markComment: >
    This issue has been automatically marked stale because of inactivity.
    It will be automatically closed in 14 days if no further activity occurs.

    This does not mean this issue is unimportant, just that it is stale.

    If you believe this issue should stay open, please add a comment explaining why it should stay open (e.g. you can still reproduce the issue or you still believe the feature is important).

pulls:
  markComment: >
    This PR has been automatically marked stale because of inactivity.
    It will be automatically closed in 14 days if no further activity occurs.

    This does not mean this PR is unimportant, just that it is stale.

    If you believe this PR should stay open, please add a comment explaining why it should stay open.
