default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: db
  database: kudos_development
  username: postgres
  port: 5432

test:
  <<: *default
  host: db
  database: kudos_test
  username: postgres

production:
  <<: *default
  host: <%= ENV.fetch("KUDOS_DB_HOST", 'db') %>
  database: <%= ENV.fetch("KUDOS_DB_NAME", 'kudos_production') %>
  username: <%= ENV.fetch("KUDOS_DB_USERNAME", 'kudos') %>
  password: <%= ENV["KUDOS_DB_PASSWORD"] %>
  port: <%= ENV.fetch("KUDOS_DB_PORT", 5432) %>
