default: &default
  host: db
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: kudos_development
  username: postgres

test:
  <<: *default
  database: kudos_test
  username: postgres

production:
  <<: *default
  database: kudos_production
  username: kudos
  password: <%= ENV['KUDOS_DATABASE_PASSWORD'] %>
